 		   <!-- Start:Footer-->
 		 <footer>
 		 	<div id="social-links" class="aligncenter">
 		 		<a href="" class="up-arrow"><i class="icon-angle-up"></i></a>
 		 		<div class="row">
 		 			<a href="#"><i class="icon-facebook icon-circled icon-64"></i></a>
 		 			<a href="#"><i class="icon-twitter icon-circled icon-64"></i></a>
 		 		</div>
 		 		<div class="copyrights">
 		 			&copy;2015  All Rights Reserved.
 		 		</div>
				 
			</div>
 		 	
 		 </footer>
 		   <!-- End:Footer-->